// JulianColors.swift
// Generated by scripts/generate-adapters.py from data/foundations.json.
// Do not edit by hand; regenerate instead.
//
// Scales are OKLCH converted to sRGB. Semantic dark values are a
// mechanical first pass; the guide documents no dark-mode opinion yet.

#if canImport(UIKit)
import UIKit

/// The perceptual gray and color scales. Prefer `JulianColor.semantic`;
/// raw scale values are the definition layer, not the component layer.
public enum JulianScale {
    // Gray
    public static let gray0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let gray50 = UIColor(red: 0.9619, green: 0.9619, blue: 0.9619, alpha: 1)  // oklch(0.97098 0 0)
    public static let gray100 = UIColor(red: 0.9190, green: 0.9190, blue: 0.9190, alpha: 1)  // oklch(0.93812 0 0)
    public static let gray200 = UIColor(red: 0.8196, green: 0.8196, blue: 0.8196, alpha: 1)  // oklch(0.86065 0 0)
    public static let gray300 = UIColor(red: 0.7041, green: 0.7041, blue: 0.7041, alpha: 1)  // oklch(0.76845 0 0)
    public static let gray400 = UIColor(red: 0.5782, green: 0.5782, blue: 0.5782, alpha: 1)  // oklch(0.66472 0 0)
    public static let gray500 = UIColor(red: 0.4498, green: 0.4498, blue: 0.4498, alpha: 1)  // oklch(0.55453 0 0)
    public static let gray600 = UIColor(red: 0.3266, green: 0.3266, blue: 0.3266, alpha: 1)  // oklch(0.4433 0 0)
    public static let gray700 = UIColor(red: 0.2142, green: 0.2142, blue: 0.2142, alpha: 1)  // oklch(0.33532 0 0)
    public static let gray800 = UIColor(red: 0.1159, green: 0.1159, blue: 0.1159, alpha: 1)  // oklch(0.23316 0 0)
    public static let gray900 = UIColor(red: 0.0339, green: 0.0339, blue: 0.0339, alpha: 1)  // oklch(0.13798 0 0)
    public static let gray950 = UIColor(red: 0.0104, green: 0.0104, blue: 0.0104, alpha: 1)  // oklch(0.0931 0 0)
    public static let gray1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Blue
    public static let blue0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let blue50 = UIColor(red: 0.9368, green: 0.9663, blue: 0.9981, alpha: 1)  // oklch(0.97103 0.0135 250)
    public static let blue100 = UIColor(red: 0.8708, green: 0.9313, blue: 0.9961, alpha: 1)  // oklch(0.94102 0.0278 250)
    public static let blue200 = UIColor(red: 0.7280, green: 0.8563, blue: 0.9921, alpha: 1)  // oklch(0.87712 0.0594 250)
    public static let blue300 = UIColor(red: 0.5637, green: 0.7718, blue: 0.9879, alpha: 1)  // oklch(0.80638 0.0962 250)
    public static let blue400 = UIColor(red: 0.3573, green: 0.6728, blue: 0.9832, alpha: 1)  // oklch(0.72628 0.1403 250)
    public static let blue500 = UIColor(red: 0.1629, green: 0.5566, blue: 0.9035, alpha: 1)  // oklch(0.63419 0.16 250)
    public static let blue600 = UIColor(red: 0.0697, green: 0.4314, blue: 0.7276, alpha: 1)  // oklch(0.52906 0.1423 250)
    public static let blue700 = UIColor(red: 0.0371, green: 0.3023, blue: 0.5196, alpha: 1)  // oklch(0.41332 0.1111 250)
    public static let blue800 = UIColor(red: 0.0128, green: 0.1765, blue: 0.3175, alpha: 1)  // oklch(0.29211 0.0786 250)
    public static let blue900 = UIColor(red: 0.0025, green: 0.0628, blue: 0.1346, alpha: 1)  // oklch(0.17012 0.0458 250)
    public static let blue950 = UIColor(red: 0.0007, green: 0.0180, blue: 0.0545, alpha: 1)  // oklch(0.10973 0.0295 250)
    public static let blue1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Red
    public static let red0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let red50 = UIColor(red: 0.9982, green: 0.9501, blue: 0.9427, alpha: 1)  // oklch(0.97103 0.0135 28)
    public static let red100 = UIColor(red: 0.9964, green: 0.8978, blue: 0.8828, alpha: 1)  // oklch(0.94102 0.0282 28)
    public static let red200 = UIColor(red: 0.9926, green: 0.7836, blue: 0.7529, alpha: 1)  // oklch(0.87712 0.0621 28)
    public static let red300 = UIColor(red: 0.9889, green: 0.6496, blue: 0.6038, alpha: 1)  // oklch(0.80638 0.1047 28)
    public static let red400 = UIColor(red: 0.9721, green: 0.4881, blue: 0.4339, alpha: 1)  // oklch(0.72628 0.1536 28)
    public static let red500 = UIColor(red: 0.8558, green: 0.3642, blue: 0.3167, alpha: 1)  // oklch(0.63419 0.16 28)
    public static let red600 = UIColor(red: 0.7027, green: 0.2446, blue: 0.2081, alpha: 1)  // oklch(0.52906 0.1536 28)
    public static let red700 = UIColor(red: 0.5222, green: 0.1364, blue: 0.1133, alpha: 1)  // oklch(0.41332 0.1344 28)
    public static let red800 = UIColor(red: 0.3285, green: 0.0521, blue: 0.0406, alpha: 1)  // oklch(0.29211 0.1024 28)
    public static let red900 = UIColor(red: 0.1379, green: 0.0126, blue: 0.0094, alpha: 1)  // oklch(0.17012 0.0576 28)
    public static let red950 = UIColor(red: 0.0495, green: 0.0062, blue: 0.0046, alpha: 1)  // oklch(0.10973 0.0304 28)
    public static let red1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Orange
    public static let orange0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let orange50 = UIColor(red: 0.9981, green: 0.9541, blue: 0.9140, alpha: 1)  // oklch(0.97103 0.0182 65)
    public static let orange100 = UIColor(red: 0.9962, green: 0.9059, blue: 0.8227, alpha: 1)  // oklch(0.94102 0.0378 65)
    public static let orange200 = UIColor(red: 0.9925, green: 0.7999, blue: 0.6165, alpha: 1)  // oklch(0.87712 0.0825 65)
    public static let orange300 = UIColor(red: 0.9842, green: 0.6763, blue: 0.3545, alpha: 1)  // oklch(0.80638 0.1344 65)
    public static let orange400 = UIColor(red: 0.9063, green: 0.5616, blue: 0.1312, alpha: 1)  // oklch(0.72628 0.1536 65)
    public static let orange500 = UIColor(red: 0.7580, green: 0.4646, blue: 0.0930, alpha: 1)  // oklch(0.63419 0.1352 65)
    public static let orange600 = UIColor(red: 0.5932, green: 0.3593, blue: 0.0629, alpha: 1)  // oklch(0.52906 0.1128 65)
    public static let orange700 = UIColor(red: 0.4210, green: 0.2493, blue: 0.0322, alpha: 1)  // oklch(0.41332 0.0881 65)
    public static let orange800 = UIColor(red: 0.2535, green: 0.1421, blue: 0.0112, alpha: 1)  // oklch(0.29211 0.0623 65)
    public static let orange900 = UIColor(red: 0.1020, green: 0.0453, blue: 0.0022, alpha: 1)  // oklch(0.17012 0.0363 65)
    public static let orange950 = UIColor(red: 0.0358, green: 0.0122, blue: 0.0006, alpha: 1)  // oklch(0.10973 0.0234 65)
    public static let orange1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Yellow
    public static let yellow0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let yellow50 = UIColor(red: 0.9799, green: 0.9664, blue: 0.8761, alpha: 1)  // oklch(0.97103 0.0304 100)
    public static let yellow100 = UIColor(red: 0.9571, green: 0.9300, blue: 0.7575, alpha: 1)  // oklch(0.94102 0.0576 100)
    public static let yellow200 = UIColor(red: 0.9019, green: 0.8493, blue: 0.5329, alpha: 1)  // oklch(0.87712 0.1024 100)
    public static let yellow300 = UIColor(red: 0.8316, green: 0.7584, blue: 0.3122, alpha: 1)  // oklch(0.80638 0.1344 100)
    public static let yellow400 = UIColor(red: 0.7368, green: 0.6573, blue: 0.1229, alpha: 1)  // oklch(0.72628 0.1434 100)
    public static let yellow500 = UIColor(red: 0.6134, green: 0.5462, blue: 0.0944, alpha: 1)  // oklch(0.63419 0.1253 100)
    public static let yellow600 = UIColor(red: 0.4779, green: 0.4244, blue: 0.0644, alpha: 1)  // oklch(0.52906 0.1045 100)
    public static let yellow700 = UIColor(red: 0.3364, green: 0.2971, blue: 0.0333, alpha: 1)  // oklch(0.41332 0.0816 100)
    public static let yellow800 = UIColor(red: 0.1986, green: 0.1731, blue: 0.0116, alpha: 1)  // oklch(0.29211 0.0577 100)
    public static let yellow900 = UIColor(red: 0.0740, green: 0.0611, blue: 0.0023, alpha: 1)  // oklch(0.17012 0.0336 100)
    public static let yellow950 = UIColor(red: 0.0224, green: 0.0174, blue: 0.0006, alpha: 1)  // oklch(0.10973 0.0217 100)
    public static let yellow1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Purple
    public static let purple0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let purple50 = UIColor(red: 0.9718, green: 0.9526, blue: 0.9982, alpha: 1)  // oklch(0.97103 0.0162 305)
    public static let purple100 = UIColor(red: 0.9430, green: 0.9034, blue: 0.9962, alpha: 1)  // oklch(0.94102 0.0333 305)
    public static let purple200 = UIColor(red: 0.8833, green: 0.7974, blue: 0.9922, alpha: 1)  // oklch(0.87712 0.0713 305)
    public static let purple300 = UIColor(red: 0.8198, green: 0.6766, blue: 0.9881, alpha: 1)  // oklch(0.80638 0.1159 305)
    public static let purple400 = UIColor(red: 0.7417, green: 0.5464, blue: 0.9535, alpha: 1)  // oklch(0.72628 0.1536 305)
    public static let purple500 = UIColor(red: 0.6325, green: 0.4286, blue: 0.8431, alpha: 1)  // oklch(0.63419 0.16 305)
    public static let purple600 = UIColor(red: 0.5044, green: 0.3102, blue: 0.6955, alpha: 1)  // oklch(0.52906 0.1536 305)
    public static let purple700 = UIColor(red: 0.3636, green: 0.1977, blue: 0.5193, alpha: 1)  // oklch(0.41332 0.1344 305)
    public static let purple800 = UIColor(red: 0.2199, green: 0.1005, blue: 0.3280, alpha: 1)  // oklch(0.29211 0.1024 305)
    public static let purple900 = UIColor(red: 0.0840, green: 0.0274, blue: 0.1373, alpha: 1)  // oklch(0.17012 0.0576 305)
    public static let purple950 = UIColor(red: 0.0247, green: 0.0095, blue: 0.0484, alpha: 1)  // oklch(0.10973 0.0304 305)
    public static let purple1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

    // Green
    public static let green0 = UIColor(red: 1.0000, green: 1.0000, blue: 1.0000, alpha: 1)  // oklch(1 0 0)
    public static let green50 = UIColor(red: 0.9155, green: 0.9857, blue: 0.9146, alpha: 1)  // oklch(0.97103 0.0304 145)
    public static let green100 = UIColor(red: 0.8332, green: 0.9664, blue: 0.8327, alpha: 1)  // oklch(0.94102 0.0576 145)
    public static let green200 = UIColor(red: 0.6748, green: 0.9135, blue: 0.6783, alpha: 1)  // oklch(0.87712 0.1024 145)
    public static let green300 = UIColor(red: 0.5241, green: 0.8415, blue: 0.5356, alpha: 1)  // oklch(0.80638 0.1344 145)
    public static let green400 = UIColor(red: 0.3803, green: 0.7499, blue: 0.4029, alpha: 1)  // oklch(0.72628 0.1536 145)
    public static let green500 = UIColor(red: 0.2416, green: 0.6376, blue: 0.2791, alpha: 1)  // oklch(0.63419 0.16 145)
    public static let green600 = UIColor(red: 0.1039, green: 0.5065, blue: 0.1650, alpha: 1)  // oklch(0.52906 0.1536 145)
    public static let green700 = UIColor(red: 0.0425, green: 0.3589, blue: 0.0979, alpha: 1)  // oklch(0.41332 0.1235 145)
    public static let green800 = UIColor(red: 0.0150, green: 0.2132, blue: 0.0440, alpha: 1)  // oklch(0.29211 0.0873 145)
    public static let green900 = UIColor(red: 0.0030, green: 0.0815, blue: 0.0088, alpha: 1)  // oklch(0.17012 0.0508 145)
    public static let green950 = UIColor(red: 0.0019, green: 0.0250, blue: 0.0032, alpha: 1)  // oklch(0.10973 0.0304 145)
    public static let green1000 = UIColor(red: 0.0016, green: 0.0016, blue: 0.0016, alpha: 1)  // oklch(0.05 0 0)

}

/// Semantic color roles from the design system's color contract.
/// Components consume these, never raw scale values.
public enum JulianColor {
    private static func dynamic(light: UIColor, dark: UIColor) -> UIColor {
        UIColor { traits in
            traits.userInterfaceStyle == .dark ? dark : light
        }
    }

    /// Light: gray.50 · dark (first pass): gray.1000
    public static let canvas = dynamic(light: JulianScale.gray50, dark: JulianScale.gray1000)
    /// Light: gray.0 · dark (first pass): gray.950
    public static let surface = dynamic(light: JulianScale.gray0, dark: JulianScale.gray950)
    /// Light: gray.50 · dark (first pass): gray.900
    public static let surfaceSubtle = dynamic(light: JulianScale.gray50, dark: JulianScale.gray900)
    /// Light: gray.100 · dark (first pass): gray.900
    public static let surfaceDisabled = dynamic(light: JulianScale.gray100, dark: JulianScale.gray900)
    /// Light: gray.1000 · dark (first pass): gray.0
    public static let surfaceInverse = dynamic(light: JulianScale.gray1000, dark: JulianScale.gray0)
    /// Light: gray.1000 · dark (first pass): gray.0
    public static let textPrimary = dynamic(light: JulianScale.gray1000, dark: JulianScale.gray0)
    /// Light: gray.600 · dark (first pass): gray.400
    public static let textSecondary = dynamic(light: JulianScale.gray600, dark: JulianScale.gray400)
    /// Light: gray.500 · dark (first pass): gray.500
    public static let textPlaceholder = dynamic(light: JulianScale.gray500, dark: JulianScale.gray500)
    /// Light: gray.500 · dark (first pass): gray.500
    public static let textDisabled = dynamic(light: JulianScale.gray500, dark: JulianScale.gray500)
    /// Light: gray.0 · dark (first pass): gray.1000
    public static let textInverse = dynamic(light: JulianScale.gray0, dark: JulianScale.gray1000)
    /// Light: gray.100 · dark (first pass): gray.900
    public static let borderSubtle = dynamic(light: JulianScale.gray100, dark: JulianScale.gray900)
    /// Light: gray.300 · dark (first pass): gray.700
    public static let borderDefault = dynamic(light: JulianScale.gray300, dark: JulianScale.gray700)
    /// Light: gray.500 · dark (first pass): gray.500
    public static let borderStrong = dynamic(light: JulianScale.gray500, dark: JulianScale.gray500)
    /// Light: blue.500 · dark (first pass): blue.400
    public static let borderFocus = dynamic(light: JulianScale.blue500, dark: JulianScale.blue400)
    /// Light: blue.500 · dark (first pass): blue.400
    public static let actionPrimary = dynamic(light: JulianScale.blue500, dark: JulianScale.blue400)
    /// Light: blue.600 · dark (first pass): blue.300
    public static let actionPrimaryHover = dynamic(light: JulianScale.blue600, dark: JulianScale.blue300)
    /// Light: gray.100 · dark (first pass): gray.900
    public static let actionSecondary = dynamic(light: JulianScale.gray100, dark: JulianScale.gray900)
    /// Light: gray.200 · dark (first pass): gray.800
    public static let actionSecondaryHover = dynamic(light: JulianScale.gray200, dark: JulianScale.gray800)
    /// Light: gray.50 · dark (first pass): gray.950
    public static let actionQuietHover = dynamic(light: JulianScale.gray50, dark: JulianScale.gray950)
    /// Light: green.600 · dark (first pass): green.400
    public static let success = dynamic(light: JulianScale.green600, dark: JulianScale.green400)
    /// Light: green.100 · dark (first pass): green.900
    public static let successSubtle = dynamic(light: JulianScale.green100, dark: JulianScale.green900)
    /// Light: orange.700 · dark (first pass): orange.400
    public static let warning = dynamic(light: JulianScale.orange700, dark: JulianScale.orange400)
    /// Light: yellow.100 · dark (first pass): yellow.900
    public static let warningSubtle = dynamic(light: JulianScale.yellow100, dark: JulianScale.yellow900)
    /// Light: red.600 · dark (first pass): red.500
    public static let danger = dynamic(light: JulianScale.red600, dark: JulianScale.red500)
    /// Light: red.100 · dark (first pass): red.900
    public static let dangerSubtle = dynamic(light: JulianScale.red100, dark: JulianScale.red900)
}
#endif
